// <auto-generated />
using System;
using HardwareMonitor.RestAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SystemMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221209015218_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAuthorised")
                        .HasColumnType("bit");

                    b.Property<string>("SystemMacs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemsInfos");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SystemInfoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SystemInfoId");

                    b.ToTable("SystemReadings");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CpuCores")
                        .HasColumnType("int");

                    b.Property<string>("CpuInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsNameVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemReadingId")
                        .HasColumnType("int");

                    b.Property<double>("TotalMemory")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SystemReadingId")
                        .IsUnique();

                    b.ToTable("SystemSpecs");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CpuTotalUsage")
                        .HasColumnType("float");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("float");

                    b.Property<int>("SystemReadingId")
                        .HasColumnType("int");

                    b.Property<double>("SystemUptime")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SystemReadingId")
                        .IsUnique();

                    b.ToTable("Usages");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.CpuPerCoreUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemUsageId")
                        .HasColumnType("int");

                    b.Property<double>("Usage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SystemUsageId");

                    b.ToTable("CpuPerCoreUsages");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.DiskSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiskSize")
                        .HasColumnType("float");

                    b.Property<int>("SystemSpecsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemSpecsId");

                    b.ToTable("DisksSpecs");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.DiskUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiskName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemUsageId")
                        .HasColumnType("int");

                    b.Property<double>("Usage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SystemUsageId");

                    b.ToTable("DiskUsages");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.NetworkSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdapterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Bandwidth")
                        .HasColumnType("float");

                    b.Property<int>("SystemSpecsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemSpecsId");

                    b.ToTable("NetworksSpecs");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.NetworkUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdapterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BytesReceived")
                        .HasColumnType("float");

                    b.Property<double>("BytesSent")
                        .HasColumnType("float");

                    b.Property<int>("SystemUsageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemUsageId");

                    b.ToTable("NetworkUsages");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemReading", b =>
                {
                    b.HasOne("HardwareMonitor.Core.Domain.SystemInfo", "SystemInfo")
                        .WithMany("SystemReadings")
                        .HasForeignKey("SystemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemInfo");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemSpecs", b =>
                {
                    b.HasOne("HardwareMonitor.Core.Domain.SystemReading", "SystemReading")
                        .WithOne("SystemSpecs")
                        .HasForeignKey("HardwareMonitor.Core.Domain.SystemSpecs", "SystemReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemReading");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemUsage", b =>
                {
                    b.HasOne("HardwareMonitor.Core.Domain.SystemReading", "SystemReading")
                        .WithOne("Usage")
                        .HasForeignKey("HardwareMonitor.Core.Domain.SystemUsage", "SystemReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemReading");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.CpuPerCoreUsage", b =>
                {
                    b.HasOne("HardwareMonitor.Core.Domain.SystemUsage", "SystemUsage")
                        .WithMany("CpuPerCoreUsage")
                        .HasForeignKey("SystemUsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUsage");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.DiskSpecs", b =>
                {
                    b.HasOne("HardwareMonitor.Core.Domain.SystemSpecs", "SystemSpecs")
                        .WithMany("DiskSpecs")
                        .HasForeignKey("SystemSpecsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemSpecs");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.DiskUsage", b =>
                {
                    b.HasOne("HardwareMonitor.Core.Domain.SystemUsage", "SystemUsage")
                        .WithMany("DiskUsage")
                        .HasForeignKey("SystemUsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUsage");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.NetworkSpecs", b =>
                {
                    b.HasOne("HardwareMonitor.Core.Domain.SystemSpecs", "SystemSpecs")
                        .WithMany("NetworkSpecs")
                        .HasForeignKey("SystemSpecsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemSpecs");
                });

            modelBuilder.Entity("SystemMonitor.Core.Domain.NetworkUsage", b =>
                {
                    b.HasOne("HardwareMonitor.Core.Domain.SystemUsage", "SystemUsage")
                        .WithMany("NetworkUsage")
                        .HasForeignKey("SystemUsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUsage");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemInfo", b =>
                {
                    b.Navigation("SystemReadings");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemReading", b =>
                {
                    b.Navigation("SystemSpecs");

                    b.Navigation("Usage");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemSpecs", b =>
                {
                    b.Navigation("DiskSpecs");

                    b.Navigation("NetworkSpecs");
                });

            modelBuilder.Entity("HardwareMonitor.Core.Domain.SystemUsage", b =>
                {
                    b.Navigation("CpuPerCoreUsage");

                    b.Navigation("DiskUsage");

                    b.Navigation("NetworkUsage");
                });
#pragma warning restore 612, 618
        }
    }
}
